export { default as DefaultTemplate } from './Default/Default'
export { default as EventDefaultTemplate } from './Event/EventDefault'
export { default as NewsAlternativeTemplate } from './News/NewsAlternative'
export { default as NewsDefaultTemplate } from './News/NewsDefault'
export { default as ProjectTemplate } from './Project/ProjectDefault'
